<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file">
    <div class="attachments">
	<?php foreach($this->attachments as $attachment): ?>
		<div class="item resource">
		<?php
		$item = $attachment->item();
		if ($item):
		?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        $sketchFab = false;
        if($item->resourceTemplate()){
            if($item->resourceTemplate()->label() == "3D Resource"){
                $sketchFab = $item->value("mods:locationUrl");
            }
        }

        if ($media && !$sketchFab):
            echo $media->render([
                'thumbnailType' => $thumbnailType,
                'link' => $link,
            ]);
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
        <?php if($sketchFab):?>
             <div>
                  <iframe width="100%" height="250px" src="<?php echo $sketchFab; ?>/embed" frameborder="0" allowvr="" allowfullscreen="true" webkitallowfullscreen="true" onmousewheel=""></iframe>
             </div>
        <?php endif;?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
    </div>
</div>
