<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    $thingLink = false;
    if($item->resourceTemplate()){
        if($item->resourceTemplate()->label() == "3D Resource"){
            $thingLink = $item->value("mods:locationUrl");
        }
    }
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media && !$thingLink):
            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle());?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($thingLink): ?>
        <iframe width="100%" height="250px" data-original-width="100%" data-original-height="250px" src=""<?php echo $thingLink; ?>" type="text/html" style="border: none;" webkitallowfullscreen mozallowfullscreen allowfullscreen scrolling="no"></iframe>
		<script async src="//cdn.thinglink.me/jse/responsive.js"></script>
		<br/>
		<a href="<?php echo $thingLink; ?>/accessibility" target="_blank" rel="noopener noreferrer">Click here to view the accessible version of this interactive content</a>
    <?php endif; ?>
    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
