<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    $thingLink = false;
    if($item->resourceTemplate()){
        if($item->resourceTemplate()->label() == "3D Resource"){
            $thingLink = $item->value("mods:locationUrl");
        }
    }
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media && !$thingLink):
            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle());?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($thingLink): ?>
        <?php if($thingLink):?>
             <div>
                 <iframe width="640" height="360" data-original-width="640" data-original-height="360" src="<?php echo $thingLink; ?>" type="text/html" style="border: none;" webkitallowfullscreen mozallowfullscreen allowfullscreen scrolling="no"></iframe>
                 <script async src="//cdn.thinglink.me/jse/responsive.js"></script>
                 <br/>
                 <a href="<?php echo $thingLink; ?>" target="_blank" rel="noopener noreferrer">Click here to view the fullsize version of this interactive content</a>
             </div>
        <?php endif;?>
    <?php endif; ?>
    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
