<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    $sketchFab = false;
    if($item->resourceTemplate()){
        if($item->resourceTemplate()->label() == "3D Resource"){
            $sketchFab = $item->value("mods:locationUrl");
        }
    }
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media && !$sketchFab):
            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle());?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($sketchFab): ?>
        <iframe width="100%" height="250px" src="<?php echo $sketchFab;?>/embed" frameborder="0" allowvr="" allowfullscreen="true" webkitallowfullscreen="true" onmousewheel=""></iframe>
    <?php endif; ?>
    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
